spring.application.name=lab2

spring.datasource.url=jdbc:postgresql://localhost:5432/ziovpo_labs
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

dev/jwt.secret=${JWT_SECRET}
jwt.access.expiration-ms=900000
jwt.refresh.expiration-ms=1209600000

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:server_cert.jks
server.ssl.key-store-type=JKS
server.ssl.key-store-password=${SERVER_PASS}
server.ssl.key-alias=server_cert
